name: Daily Capacity Workflow

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  build:
   runs-on: [self-hosted, windows]
   strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.10.12']

   steps:
        - name: Checkout repo without cleaning
          uses: actions/checkout@v4

        - name: Install dependencies
          run: pip install pandas numpy openpyxl
        
        - name: Run PowerShell script
          run:  pwsh -File ./script_powershell.ps1
          shell: cmd
