name: Daily Capacity Workflow

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: [self-hosted, windows]

    steps:
  
      - name: Checkout repo without cleaning
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pandas numpy openpyxl
        
      - name: Run PowerShell script
        run:  pwsh -File ./script_powershell.ps1
        shell: cmd
